manifests:
- manifest: data/manifests/la_train.csv
  protocol: LA/LA/ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.train.trn.txt
  scenario: LA
  split: train
  rows: 25380
  missing_audio: 0
- manifest: data/manifests/la_dev.csv
  protocol: LA/LA/ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.dev.trl.txt
  scenario: LA
  split: dev
  rows: 24844
  missing_audio: 0
- manifest: data/manifests/la_eval.csv
  protocol: LA/LA/ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.eval.trl.txt
  scenario: LA
  split: eval
  rows: 71237
  missing_audio: 0
- manifest: data/manifests/pa_train.csv
  protocol: PA/PA/ASVspoof2019_PA_cm_protocols/ASVspoof2019.PA.cm.train.trn.txt
  scenario: PA
  split: train
  rows: 54000
  missing_audio: 0
- manifest: data/manifests/pa_dev.csv
  protocol: PA/PA/ASVspoof2019_PA_cm_protocols/ASVspoof2019.PA.cm.dev.trl.txt
  scenario: PA
  split: dev
  rows: 29700
  missing_audio: 0
- manifest: data/manifests/pa_eval.csv
  protocol: PA/PA/ASVspoof2019_PA_cm_protocols/ASVspoof2019.PA.cm.eval.trl.txt
  scenario: PA
  split: eval
  rows: 134730
  missing_audio: 0
